#!/usr/bin/env bash
# Generates a meson cross-file for a given Android ABI, targeting the
# unified NDK toolchain (NDK r23+). Run on a machine/CI runner with
# ANDROID_NDK_HOME set -- this sandbox does not have the NDK, so this
# script is exercised by .github/workflows/native-libs.yml, not locally.
#
# Usage: gen-cross-file.sh <abi> <api-level> <output-path>
#   abi: arm64-v8a | armeabi-v7a | x86_64
set -euo pipefail

ABI="${1:?Usage: gen-cross-file.sh <abi> <api-level> <output-path>}"
API="${2:?missing api level}"
OUT="${3:?missing output path}"

: "${ANDROID_NDK_HOME:?ANDROID_NDK_HOME must be set}"

HOST_TAG="linux-x86_64"
TOOLCHAIN="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/${HOST_TAG}"
BIN="${TOOLCHAIN}/bin"

case "$ABI" in
  arm64-v8a)
    TRIPLE="aarch64-linux-android"
    CPU_FAMILY="aarch64"
    CPU="aarch64"
    ;;
  armeabi-v7a)
    TRIPLE="armv7a-linux-androideabi"
    CPU_FAMILY="arm"
    CPU="armv7a"
    ;;
  x86_64)
    TRIPLE="x86_64-linux-android"
    CPU_FAMILY="x86_64"
    CPU="x86_64"
    ;;
  *)
    echo "Unsupported ABI: $ABI" >&2
    exit 1
    ;;
esac

CC="${BIN}/${TRIPLE}${API}-clang"
CXX="${BIN}/${TRIPLE}${API}-clang++"

for tool in "$CC" "$CXX"; do
  if [[ ! -x "$tool" ]]; then
    echo "Expected NDK clang wrapper not found: $tool" >&2
    echo "Check ANDROID_NDK_HOME / API level / ABI combination." >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# Auto-generated by scripts/gen-cross-file.sh -- do not edit by hand.
[binaries]
c = '${CC}'
cpp = '${CXX}'
ar = '${BIN}/llvm-ar'
strip = '${BIN}/llvm-strip'
ranlib = '${BIN}/llvm-ranlib'
pkgconfig = 'pkg-config'

[built-in options]
c_args = []
c_link_args = []
cpp_args = []
cpp_link_args = []

[host_machine]
system = 'android'
cpu_family = '${CPU_FAMILY}'
cpu = '${CPU}'
endian = 'little'

[properties]
needs_exe_wrapper = true
EOF

echo "Wrote cross-file: $OUT"
